import type { Language } from "../../i18n/core";

export type OnboardingExpansionCopy = {
  b05: string;
  b06: string;
  b06Cta: string;
  d01: string;
  d01Cta: string;
  d08: string;
  d09: string;
  d10: string;
  d11: string;
};

export const ONBOARDING_EXPANSION_COPY: Record<Language, OnboardingExpansionCopy> = {
  en: {
    b05: "After 8 seconds, follow the arrow and collect it. The new tier-2 pet starts at Lv1.",
    b06: "All six base-attribute pets have arrived at max level. They do not use backyard capacity.",
    b06Cta: "Welcome all six",
    d01: "The first factory lesson is complete. Return to the main screen for the next operation.",
    d01Cta: "Return to main",
    d08: "Unlock one more hatch pit. This tutorial upgrade is fully reimbursed.",
    d09: "Follow the arrow and walk to the backyard upgrade sign, then upgrade once. This tutorial upgrade is fully reimbursed.",
    d10: "Complete the two highlighted classic recipes in a row. Both are free and finish within 8 seconds.",
    d11: "Both fusion results have been collected. Return to the main screen for the second factory lesson.",
  },
  "zh-Hans": {
    b05: "8 秒后跟箭头回去点【收取】。融合出的二阶宠物会从 Lv1 开始成长。",
    b06: "六个基础属性的满级宠物已经全部送达，而且都不占后院容量。",
    b06Cta: "收下六只满级宠物",
    d01: "第一次工厂游戏引导已经完成。请返回主界面，继续后续操作。",
    d01Cta: "返回主界面",
    d08: "解锁一个新的孵化蛋坑。这次引导升级会全额报销。",
    d09: "跟着箭头走到后院升级牌，再升级一次后院。这次引导升级同样会全额报销。",
    d10: "按高亮提示连续完成两个新的经典配方。两次融合都免费，并会在 8 秒内完成。",
    d11: "两只融合结果都已收取。返回主界面，开始第二次工厂游戏引导。",
  },
  "zh-Hant": {
    b05: "8 秒後跟著箭頭回去點【收取】。融合出的二階寵物會從 Lv1 開始成長。",
    b06: "六隻基礎屬性的滿級寵物已全部送達，而且都不占後院容量。",
    b06Cta: "收下六隻滿級寵物",
    d01: "第一次工廠遊戲教學已完成。請返回主畫面，繼續後續操作。",
    d01Cta: "返回主畫面",
    d08: "解鎖一個新的孵化蛋坑。這次教學升級會全額補助。",
    d09: "跟著箭頭走到後院升級牌，再升級一次後院。這次教學升級同樣會全額補助。",
    d10: "依照高亮提示連續完成兩個新的經典配方。兩次融合都免費，並會在 8 秒內完成。",
    d11: "兩隻融合結果都已收取。返回主畫面，開始第二次工廠遊戲教學。",
  },
  ja: {
    b05: "8秒後、矢印をたどって【受け取る】を選びましょう。新しい★2ペットはLv1から始まります。",
    b06: "基本6属性のペットが1匹ずつ、すべて最大レベルで届きました。裏庭の収容枠も使いません。",
    b06Cta: "6匹を迎える",
    d01: "1回目の工場チュートリアルは完了です。次の操作のため、メイン画面へ戻りましょう。",
    d01Cta: "メイン画面へ戻る",
    d08: "ふ化スペースを1つ解放しましょう。このチュートリアル中の費用は全額補助されます。",
    d09: "矢印に従って裏庭のアップグレード看板まで歩き、1回アップグレードしましょう。費用は全額補助されます。",
    d10: "ハイライトされた2つの新しい定番レシピを続けて合成しましょう。どちらも無料で、8秒以内に完了します。",
    d11: "2つの合成結果を両方受け取りました。メイン画面へ戻り、2回目の工場チュートリアルを始めましょう。",
  },
  ko: {
    b05: "8초 뒤 화살표를 따라가 【받기】를 누르세요. 새 2성 펫은 Lv1부터 성장합니다.",
    b06: "기본 속성 6종의 펫이 모두 최고 레벨로 한 마리씩 도착했습니다. 뒷마당 수용량도 차지하지 않습니다.",
    b06Cta: "여섯 마리 맞이하기",
    d01: "첫 번째 공장 튜토리얼을 마쳤습니다. 다음 작업을 위해 메인 화면으로 돌아가세요.",
    d01Cta: "메인 화면으로",
    d08: "부화 구덩이를 하나 더 잠금 해제하세요. 튜토리얼 업그레이드 비용은 전액 지원됩니다.",
    d09: "화살표를 따라 뒷마당 업그레이드 표지판까지 걸어간 뒤 한 번 업그레이드하세요. 비용은 전액 지원됩니다.",
    d10: "강조 표시된 새로운 클래식 레시피 두 개를 연속으로 융합하세요. 둘 다 무료이며 8초 안에 완료됩니다.",
    d11: "융합 결과 두 개를 모두 받았습니다. 메인 화면으로 돌아가 두 번째 공장 튜토리얼을 시작하세요.",
  },
  fr: {
    b05: "Après 8 secondes, suivez la flèche et récupérez-le. Le nouveau familier de rang 2 commence au niveau 1.",
    b06: "Un familier de chacun des six attributs de base vient d'arriver au niveau maximum. Ils n'occupent aucune place dans l'arrière-cour.",
    b06Cta: "Accueillir les six",
    d01: "Le premier didacticiel de l'usine est terminé. Revenez à l'écran principal pour poursuivre.",
    d01Cta: "Revenir à l'accueil",
    d08: "Déverrouillez un emplacement d'incubation. Cette amélioration du didacticiel est entièrement remboursée.",
    d09: "Suivez la flèche jusqu'au panneau d'amélioration de l'arrière-cour, puis améliorez-la une fois. Le coût est entièrement remboursé.",
    d10: "Enchaînez les deux nouvelles recettes classiques indiquées. Elles sont gratuites et se terminent en moins de 8 secondes.",
    d11: "Les deux résultats de fusion ont été récupérés. Revenez à l'accueil pour le second didacticiel de l'usine.",
  },
  de: {
    b05: "Folge nach 8 Sekunden dem Pfeil und hole es ab. Das neue Zwei-Sterne-Haustier beginnt auf Stufe 1.",
    b06: "Von jedem der sechs Grundattribute ist ein Haustier auf Höchststufe angekommen. Sie belegen keinen Platz im Hinterhof.",
    b06Cta: "Alle sechs aufnehmen",
    d01: "Das erste Fabrik-Tutorial ist abgeschlossen. Kehre für den nächsten Schritt zum Hauptbildschirm zurück.",
    d01Cta: "Zum Hauptbildschirm",
    d08: "Schalte eine weitere Brutgrube frei. Diese Tutorial-Aufwertung wird vollständig erstattet.",
    d09: "Folge dem Pfeil zum Hinterhof-Ausbauschild und werte den Hinterhof einmal auf. Die Kosten werden vollständig erstattet.",
    d10: "Führe die beiden markierten neuen klassischen Rezepte direkt nacheinander aus. Beide sind kostenlos und nach spätestens 8 Sekunden fertig.",
    d11: "Beide Fusionsergebnisse wurden abgeholt. Kehre für das zweite Fabrik-Tutorial zum Hauptbildschirm zurück.",
  },
  "es-ES": {
    b05: "Tras 8 segundos, sigue la flecha y recógelo. La nueva mascota de 2 estrellas empieza en el nivel 1.",
    b06: "Ha llegado una mascota de nivel máximo de cada uno de los seis atributos básicos. No ocupan espacio en el patio.",
    b06Cta: "Recibir a las seis",
    d01: "Has terminado el primer tutorial de la fábrica. Vuelve a la pantalla principal para continuar.",
    d01Cta: "Volver al inicio",
    d08: "Desbloquea un hueco de incubación más. El coste de esta mejora del tutorial se reembolsa por completo.",
    d09: "Sigue la flecha hasta el cartel de mejora del patio y mejóralo una vez. El coste se reembolsa por completo.",
    d10: "Completa seguidas las dos recetas clásicas nuevas que están resaltadas. Ambas son gratis y terminan en menos de 8 segundos.",
    d11: "Has recogido los dos resultados de fusión. Vuelve al inicio para el segundo tutorial de la fábrica.",
  },
  "es-419": {
    b05: "Después de 8 segundos, sigue la flecha y recógelo. La nueva mascota de 2 estrellas empieza en el nivel 1.",
    b06: "Llegó una mascota de nivel máximo de cada uno de los seis atributos básicos. No ocupan espacio en el patio.",
    b06Cta: "Recibir a las seis",
    d01: "Terminaste el primer tutorial de la fábrica. Regresa a la pantalla principal para continuar.",
    d01Cta: "Volver al inicio",
    d08: "Desbloquea un espacio de incubación más. El costo de esta mejora del tutorial se reembolsa por completo.",
    d09: "Sigue la flecha hasta el cartel de mejora del patio y mejóralo una vez. El costo se reembolsa por completo.",
    d10: "Completa seguidas las dos recetas clásicas nuevas resaltadas. Ambas son gratis y terminan en menos de 8 segundos.",
    d11: "Recogiste los dos resultados de fusión. Regresa al inicio para el segundo tutorial de la fábrica.",
  },
  "pt-BR": {
    b05: "Após 8 segundos, siga a seta e recolha o resultado. O novo pet de 2 estrelas começa no nível 1.",
    b06: "Chegou um pet no nível máximo de cada um dos seis atributos básicos. Eles não ocupam espaço no quintal.",
    b06Cta: "Receber os seis",
    d01: "O primeiro tutorial da fábrica terminou. Volte à tela principal para continuar.",
    d01Cta: "Voltar ao início",
    d08: "Desbloqueie mais um espaço de incubação. O custo desta melhoria do tutorial será reembolsado por completo.",
    d09: "Siga a seta até a placa de melhoria do quintal e melhore-o uma vez. O custo será reembolsado por completo.",
    d10: "Faça em sequência as duas novas receitas clássicas destacadas. Ambas são grátis e terminam em até 8 segundos.",
    d11: "Os dois resultados da fusão foram coletados. Volte ao início para o segundo tutorial da fábrica.",
  },
  "pt-PT": {
    b05: "Após 8 segundos, segue a seta e recolhe o resultado. A nova mascote de 2 estrelas começa no nível 1.",
    b06: "Chegou uma mascote no nível máximo de cada um dos seis atributos básicos. Não ocupam espaço no quintal.",
    b06Cta: "Receber as seis",
    d01: "O primeiro tutorial da fábrica terminou. Volta ao ecrã principal para continuar.",
    d01Cta: "Voltar ao início",
    d08: "Desbloqueia mais um espaço de incubação. O custo desta melhoria do tutorial é reembolsado por inteiro.",
    d09: "Segue a seta até à placa de melhoria do quintal e melhora-o uma vez. O custo é reembolsado por inteiro.",
    d10: "Faz de seguida as duas novas receitas clássicas assinaladas. Ambas são grátis e terminam em até 8 segundos.",
    d11: "Os dois resultados da fusão foram recolhidos. Volta ao início para o segundo tutorial da fábrica.",
  },
  ru: {
    b05: "Через 8 секунд следуйте по стрелке и заберите результат. Новый питомец 2-го ранга начинает с 1-го уровня.",
    b06: "По одному питомцу каждого из шести базовых атрибутов прибыли с максимальным уровнем. Они не занимают места во дворе.",
    b06Cta: "Принять всех шестерых",
    d01: "Первое обучение на фабрике завершено. Вернитесь на главный экран, чтобы продолжить.",
    d01Cta: "На главный экран",
    d08: "Откройте ещё одно место для инкубации. Стоимость этого улучшения полностью компенсируется.",
    d09: "Следуйте по стрелке к табличке улучшения двора, затем улучшите двор один раз. Стоимость полностью компенсируется.",
    d10: "Выполните подряд два выделенных новых классических рецепта. Оба бесплатны и завершаются не дольше чем за 8 секунд.",
    d11: "Оба результата слияния получены. Вернитесь на главный экран ко второму обучению на фабрике.",
  },
  it: {
    b05: "Dopo 8 secondi, segui la freccia e ritiralo. Il nuovo pet a 2 stelle parte dal livello 1.",
    b06: "È arrivato un pet al livello massimo per ciascuno dei sei attributi base. Non occupano spazio nel cortile.",
    b06Cta: "Accogli tutti e sei",
    d01: "Il primo tutorial della fabbrica è completo. Torna alla schermata principale per continuare.",
    d01Cta: "Torna alla schermata principale",
    d08: "Sblocca un altro spazio d'incubazione. Il costo di questo potenziamento del tutorial viene rimborsato interamente.",
    d09: "Segui la freccia fino al cartello di potenziamento del cortile, poi potenzialo una volta. Il costo viene rimborsato interamente.",
    d10: "Completa di seguito le due nuove ricette classiche evidenziate. Sono entrambe gratuite e terminano entro 8 secondi.",
    d11: "Hai ritirato entrambi i risultati delle fusioni. Torna alla schermata principale per il secondo tutorial della fabbrica.",
  },
  pl: {
    b05: "Po 8 sekundach idź za strzałką i odbierz wynik. Nowy pupil 2. rangi zaczyna od poziomu 1.",
    b06: "Przybył jeden pupil na maksymalnym poziomie dla każdego z sześciu podstawowych atrybutów. Nie zajmują miejsca na podwórku.",
    b06Cta: "Przyjmij całą szóstkę",
    d01: "Pierwszy samouczek fabryki jest ukończony. Wróć do ekranu głównego, aby kontynuować.",
    d01Cta: "Wróć do ekranu głównego",
    d08: "Odblokuj jeszcze jedno miejsce inkubacji. Koszt tego ulepszenia w samouczku zostanie w pełni zwrócony.",
    d09: "Idź za strzałką do tablicy ulepszenia podwórka, a następnie ulepsz je raz. Koszt zostanie w pełni zwrócony.",
    d10: "Wykonaj kolejno dwa podświetlone nowe klasyczne przepisy. Oba są darmowe i kończą się w ciągu 8 sekund.",
    d11: "Odebrano oba wyniki fuzji. Wróć do ekranu głównego na drugi samouczek fabryki.",
  },
  tr: {
    b05: "8 saniye sonra oku takip edip sonucu al. Yeni 2 yıldızlı evcil hayvan 1. seviyeden başlar.",
    b06: "Altı temel özelliğin her biri için birer evcil hayvan en yüksek seviyede geldi. Arka bahçe kapasitesini kullanmazlar.",
    b06Cta: "Altısını da karşıla",
    d01: "İlk fabrika öğreticisi tamamlandı. Devam etmek için ana ekrana dön.",
    d01Cta: "Ana ekrana dön",
    d08: "Bir kuluçka çukurunun daha kilidini aç. Bu öğretici yükseltmesinin ücreti tamamen karşılanır.",
    d09: "Oku takip ederek arka bahçe yükseltme tabelasına yürü, ardından bahçeyi bir kez yükselt. Ücret tamamen karşılanır.",
    d10: "Vurgulanan iki yeni klasik tarifi art arda tamamla. İkisi de ücretsizdir ve en geç 8 saniyede biter.",
    d11: "İki füzyon sonucu da alındı. İkinci fabrika öğreticisi için ana ekrana dön.",
  },
  uk: {
    b05: "Через 8 секунд ідіть за стрілкою та заберіть результат. Новий улюбленець 2-го рангу починає з 1-го рівня.",
    b06: "По одному улюбленцю кожного з шести базових атрибутів прибули з максимальним рівнем. Вони не займають місця на подвір'ї.",
    b06Cta: "Прийняти всіх шістьох",
    d01: "Перше навчання на фабриці завершено. Поверніться на головний екран, щоб продовжити.",
    d01Cta: "На головний екран",
    d08: "Відкрийте ще одне місце для інкубації. Вартість цього навчального поліпшення повністю компенсується.",
    d09: "Ідіть за стрілкою до таблички поліпшення подвір'я, а потім поліпште його один раз. Вартість повністю компенсується.",
    d10: "Виконайте поспіль два виділені нові класичні рецепти. Обидва безкоштовні й завершуються не довше ніж за 8 секунд.",
    d11: "Обидва результати злиття отримано. Поверніться на головний екран до другого навчання на фабриці.",
  },
  ar: {
    b05: "بعد 8 ثوانٍ، اتبع السهم واستلم النتيجة. يبدأ الحيوان الأليف الجديد من الرتبة الثانية عند المستوى 1.",
    b06: "وصل حيوان أليف بأقصى مستوى لكل واحدة من السمات الأساسية الست. ولن يشغلوا أي مساحة في الفناء الخلفي.",
    b06Cta: "استقبال الستة",
    d01: "اكتمل الدرس الأول للمصنع. عُد إلى الشاشة الرئيسية لمتابعة الخطوات التالية.",
    d01Cta: "العودة إلى الرئيسية",
    d08: "افتح حفرة حضانة إضافية. ستُعوَّض تكلفة ترقية الدرس بالكامل.",
    d09: "اتبع السهم وامشِ إلى لافتة ترقية الفناء الخلفي، ثم طوّره مرة واحدة. ستُعوَّض التكلفة بالكامل.",
    d10: "أكمل وصفتي الدمج الكلاسيكيتين الجديدتين والمحدّدتين تباعًا. كلتاهما مجانيتان وتكتملان خلال 8 ثوانٍ.",
    d11: "استلمت نتيجتي الدمج كلتيهما. عُد إلى الرئيسية لبدء درس المصنع الثاني.",
  },
  th: {
    b05: "หลัง 8 วินาที ให้ตามลูกศรไปกดรับ สัตว์เลี้ยง 2 ดาวตัวใหม่จะเริ่มเติบโตจาก Lv1",
    b06: "สัตว์เลี้ยงธาตุพื้นฐานทั้งหกแบบมาถึงแล้วแบบละหนึ่งตัวที่เลเวลสูงสุด และไม่ใช้ความจุของสวนหลังบ้าน",
    b06Cta: "รับทั้งหกตัว",
    d01: "บทสอนโรงงานครั้งแรกเสร็จแล้ว กลับไปหน้าหลักเพื่อทำขั้นตอนต่อไป",
    d01Cta: "กลับหน้าหลัก",
    d08: "ปลดล็อกหลุมฟักเพิ่มหนึ่งหลุม ค่าอัปเกรดในบทสอนนี้ได้รับคืนเต็มจำนวน",
    d09: "เดินตามลูกศรไปที่ป้ายอัปเกรดสวนหลังบ้าน แล้วอัปเกรดหนึ่งครั้ง ค่าใช้จ่ายจะคืนให้เต็มจำนวน",
    d10: "ผสมตามสูตรคลาสสิกใหม่สองสูตรที่ไฮไลต์ไว้ต่อเนื่องกัน ทั้งคู่ฟรีและเสร็จภายใน 8 วินาที",
    d11: "รับผลลัพธ์จากการผสมครบทั้งสองตัวแล้ว กลับหน้าหลักเพื่อเริ่มบทสอนโรงงานครั้งที่สอง",
  },
  vi: {
    b05: "Sau 8 giây, đi theo mũi tên và nhận kết quả. Thú cưng 2 sao mới sẽ bắt đầu từ cấp 1.",
    b06: "Mỗi thuộc tính cơ bản trong sáu loại đều được tặng một thú cưng cấp tối đa. Chúng không chiếm sức chứa sân sau.",
    b06Cta: "Nhận cả sáu",
    d01: "Hướng dẫn nhà máy lần đầu đã hoàn tất. Hãy trở về màn hình chính để tiếp tục.",
    d01Cta: "Về màn hình chính",
    d08: "Mở khóa thêm một ô ấp trứng. Chi phí nâng cấp trong hướng dẫn này được hoàn lại toàn bộ.",
    d09: "Đi theo mũi tên đến bảng nâng cấp sân sau, rồi nâng cấp một lần. Chi phí sẽ được hoàn lại toàn bộ.",
    d10: "Thực hiện liên tiếp hai công thức cổ điển mới đang được đánh dấu. Cả hai đều miễn phí và hoàn tất trong vòng 8 giây.",
    d11: "Đã nhận cả hai kết quả dung hợp. Hãy về màn hình chính để bắt đầu hướng dẫn nhà máy lần hai.",
  },
  id: {
    b05: "Setelah 8 detik, ikuti panah lalu ambil hasilnya. Peliharaan bintang 2 yang baru mulai dari level 1.",
    b06: "Satu peliharaan level maksimum untuk masing-masing dari enam atribut dasar telah tiba. Mereka tidak memakai kapasitas halaman belakang.",
    b06Cta: "Terima keenamnya",
    d01: "Tutorial pabrik pertama selesai. Kembali ke layar utama untuk melanjutkan.",
    d01Cta: "Kembali ke layar utama",
    d08: "Buka satu lubang penetasan lagi. Biaya peningkatan tutorial ini diganti sepenuhnya.",
    d09: "Ikuti panah dan berjalanlah ke papan peningkatan halaman belakang, lalu tingkatkan sekali. Biayanya diganti sepenuhnya.",
    d10: "Selesaikan dua resep klasik baru yang disorot secara berurutan. Keduanya gratis dan selesai dalam waktu 8 detik.",
    d11: "Kedua hasil fusi sudah diambil. Kembali ke layar utama untuk tutorial pabrik kedua.",
  },
  nl: {
    b05: "Volg na 8 seconden de pijl en haal het resultaat op. Het nieuwe huisdier van rang 2 begint op niveau 1.",
    b06: "Voor elk van de zes basiseigenschappen is een huisdier op het hoogste niveau aangekomen. Ze nemen geen ruimte in de achtertuin in.",
    b06Cta: "Alle zes verwelkomen",
    d01: "De eerste fabriekshandleiding is voltooid. Ga terug naar het hoofdscherm om verder te gaan.",
    d01Cta: "Naar het hoofdscherm",
    d08: "Ontgrendel nog een broedkuil. De kosten van deze tutorial-upgrade worden volledig vergoed.",
    d09: "Volg de pijl en loop naar het upgradebord in de achtertuin. Upgrade daarna één keer; de kosten worden volledig vergoed.",
    d10: "Voer de twee gemarkeerde nieuwe klassieke recepten direct na elkaar uit. Beide zijn gratis en binnen 8 seconden klaar.",
    d11: "Beide fusieresultaten zijn opgehaald. Ga terug naar het hoofdscherm voor de tweede fabriekshandleiding.",
  },
};

/** D10 stays active after both commits until both highlighted eggs are actually collected. */
export const ONBOARDING_GUIDED_EGG_COLLECT_COPY: Record<Language, string> = {
  en: "Both classic fusions are complete. Stay in the backyard and collect both highlighted eggs before the second factory lesson.",
  "zh-Hans": "两次经典融合都已完成。先留在后院，收取两颗高亮的融合蛋，再开始第二次工厂游戏引导。",
  "zh-Hant": "兩次經典融合都已完成。先留在後院，收取兩顆高亮的融合蛋，再開始第二次工廠遊戲教學。",
  ja: "2つの定番合成が完了しました。2回目の工場チュートリアルへ進む前に、裏庭でハイライトされたタマゴを両方受け取りましょう。",
  ko: "클래식 융합 두 번이 끝났습니다. 두 번째 공장 튜토리얼 전에 뒷마당에서 강조된 알 두 개를 모두 받으세요.",
  fr: "Les deux fusions classiques sont terminées. Restez dans l'arrière-cour et récupérez les deux œufs indiqués avant le second didacticiel de l'usine.",
  de: "Beide klassischen Fusionen sind abgeschlossen. Bleib im Hinterhof und hole beide markierten Eier ab, bevor das zweite Fabrik-Tutorial beginnt.",
  "es-ES": "Las dos fusiones clásicas han terminado. Quédate en el patio y recoge los dos huevos resaltados antes del segundo tutorial de la fábrica.",
  "es-419": "Las dos fusiones clásicas terminaron. Quédate en el patio y recoge los dos huevos resaltados antes del segundo tutorial de la fábrica.",
  "pt-BR": "As duas fusões clássicas terminaram. Fique no quintal e colete os dois ovos destacados antes do segundo tutorial da fábrica.",
  "pt-PT": "As duas fusões clássicas terminaram. Fica no quintal e recolhe os dois ovos assinalados antes do segundo tutorial da fábrica.",
  ru: "Оба классических слияния завершены. Останьтесь во дворе и заберите оба выделенных яйца до второго обучения на фабрике.",
  it: "Le due fusioni classiche sono complete. Resta nel cortile e ritira entrambe le uova evidenziate prima del secondo tutorial della fabbrica.",
  pl: "Obie klasyczne fuzje są ukończone. Zostań na podwórku i odbierz oba podświetlone jaja przed drugim samouczkiem fabryki.",
  tr: "İki klasik füzyon da tamamlandı. İkinci fabrika öğreticisinden önce arka bahçede kalıp vurgulanan iki yumurtayı da al.",
  uk: "Обидва класичні злиття завершено. Залишайтеся на подвір'ї та заберіть обидва виділені яйця до другого навчання на фабриці.",
  ar: "اكتمل الدمجان الكلاسيكيان. ابقَ في الفناء الخلفي واستلم البيضتين المحددتين قبل درس المصنع الثاني.",
  th: "ผสมสูตรคลาสสิกครบสองครั้งแล้ว อยู่ในสวนหลังบ้านและรับไข่ที่ไฮไลต์ทั้งสองใบก่อนเริ่มบทสอนโรงงานครั้งที่สอง",
  vi: "Hai lần dung hợp cổ điển đã hoàn tất. Hãy ở lại sân sau và nhận cả hai trứng được đánh dấu trước hướng dẫn nhà máy lần hai.",
  id: "Kedua fusi klasik selesai. Tetap di halaman belakang dan ambil kedua telur yang disorot sebelum tutorial pabrik kedua.",
  nl: "Beide klassieke fusies zijn voltooid. Blijf in de achtertuin en haal beide gemarkeerde eieren op vóór de tweede fabriekshandleiding.",
};

/** F01 enters the yard first; the board opens only after the player walks there. */
export const ONBOARDING_NOTICE_BOARD_CTA: Record<Language, string> = {
  en: "Go to the Notice Board",
  "zh-Hans": "前往公告板",
  "zh-Hant": "前往公告板",
  ja: "掲示板へ向かう",
  ko: "게시판으로 이동",
  fr: "Aller au panneau",
  de: "Zum Schwarzen Brett",
  "es-ES": "Ir al tablón",
  "es-419": "Ir al tablón",
  "pt-BR": "Ir ao quadro",
  "pt-PT": "Ir ao quadro",
  ru: "Идти к доске",
  it: "Vai alla bacheca",
  pl: "Idź do tablicy",
  tr: "Panoya git",
  uk: "Іти до дошки",
  ar: "اذهب إلى اللوحة",
  th: "ไปที่กระดาน",
  vi: "Đi đến bảng",
  id: "Pergi ke papan",
  nl: "Naar het prikbord",
};

export const ONBOARDING_TIER1_SWITCH_COPY: Record<Language, string> = {
  en: "First switch to the highlighted max-level tier-1 pet. Do not take a tier-2 pet into this classic fusion.",
  "zh-Hans": "先切换到高亮的满级一阶宠物。不要拿二阶宠物参加这次经典融合。",
  "zh-Hant": "先切換到高亮的滿級一階寵物。不要拿二階寵物參加這次經典融合。",
  ja: "まず、強調表示された最大レベルの第1段階ペットに切り替えてください。この定番合成に第2段階ペットは使いません。",
  ko: "먼저 강조된 최고 레벨 1단계 펫으로 전환하세요. 이번 클래식 융합에는 2단계 펫을 데려가지 마세요.",
  fr: "Passez d'abord au familier de rang 1 au niveau maximum qui est indiqué. N'utilisez pas un familier de rang 2 pour cette fusion classique.",
  de: "Wechsle zuerst zum markierten Tier-1-Haustier auf Höchststufe. Nimm kein Tier-2-Haustier für diese klassische Fusion.",
  "es-ES": "Primero cambia a la mascota de rango 1 y nivel máximo resaltada. No uses una mascota de rango 2 en esta fusión clásica.",
  "es-419": "Primero cambia a la mascota de rango 1 y nivel máximo resaltada. No uses una mascota de rango 2 en esta fusión clásica.",
  "pt-BR": "Primeiro, troque para o pet de nível máximo e categoria 1 destacado. Não use um pet de categoria 2 nesta fusão clássica.",
  "pt-PT": "Primeiro, muda para a mascote de nível máximo e categoria 1 destacada. Não uses uma mascote de categoria 2 nesta fusão clássica.",
  ru: "Сначала переключитесь на выделенного питомца 1-го ранга максимального уровня. Не берите питомца 2-го ранга в это классическое слияние.",
  it: "Prima passa al pet di rango 1 al livello massimo evidenziato. Non usare un pet di rango 2 per questa fusione classica.",
  pl: "Najpierw przełącz się na podświetlonego pupila 1. rangi na maksymalnym poziomie. Nie używaj pupila 2. rangi w tej klasycznej fuzji.",
  tr: "Önce vurgulanan en yüksek seviyeli 1. kademe evcil hayvana geç. Bu klasik füzyonda 2. kademe evcil hayvan kullanma.",
  uk: "Спочатку перемкніться на виділеного улюбленця 1-го рангу максимального рівня. Не беріть улюбленця 2-го рангу в це класичне злиття.",
  ar: "بدّل أولًا إلى الحيوان المميز من الرتبة الأولى وبأقصى مستوى. لا تستخدم حيوانًا من الرتبة الثانية في هذا الدمج الكلاسيكي.",
  th: "ก่อนอื่นให้สลับไปใช้สัตว์เลี้ยงขั้น 1 เลเวลสูงสุดที่ไฮไลต์ไว้ อย่าใช้สัตว์เลี้ยงขั้น 2 ในการผสมสูตรคลาสสิกครั้งนี้",
  vi: "Trước tiên, hãy chuyển sang thú cưng bậc 1 cấp tối đa đang được đánh dấu. Không dùng thú cưng bậc 2 cho lần dung hợp cổ điển này.",
  id: "Pertama, ganti ke peliharaan tingkat 1 level maksimum yang disorot. Jangan gunakan peliharaan tingkat 2 untuk fusi klasik ini.",
  nl: "Schakel eerst over naar het gemarkeerde huisdier van rang 1 op het hoogste niveau. Gebruik geen huisdier van rang 2 voor deze klassieke fusie.",
};
